version: "1.0"
info:
  model: int-scaffold
packages:
- name: ProjectSekhar1Project
  gitServerName: GitTest
  gitUrl: https://github.com/y509522/ProjectSekhar1Project
  gitUsername: y509522
  gitBranch: main
